### ISSUE TITLE
frequent socket hangups

### ISSUE THREAD

**Issue by tj** [Automattic/knox#116]
<3 node

```
Error: socket hang up
    at createHangUpError (http.js:1264:15)
    at CleartextStream.socketCloseListener (http.js:1315:23)
    at CleartextStream.EventEmitter.emit [as emit] (events.js:126:20)
    at SecurePair.destroy (tls.js:938:22)
    at process.startup.processNextTick.process._tickCallback [as _tickCallback] (node.js:244:9)
---------------------------------------------
    at registerReqListeners (/home/vagrant/projects/thumbs/node_modules/knox/lib/client.js:38:7)
    at Client.Client.putStream [as putStream] (/home/vagrant/projects/thumbs/node_modules/knox/lib/client.js:264:3)
    at Client.putFile (/home/vagrant/projects/thumbs/node_modules/knox/lib/client.js:232:20)
    at Object.oncomplete (fs.js:297:15)
```

looking into it, seems ridiculous to accuse s3 here, but it wouldn't surprise me either way

**Comment by riyadhalnur** [comment]
I found this [http://stackoverflow.com/questions/27392923/uploading-to-s3-with-node-knox-socket-hang-up](http://stackoverflow.com/questions/27392923/uploading-to-s3-with-node-knox-socket-hang-up) when searching for a solution into this problem. Looks like a lot of people have this problem with our good ol' friend S3.

```js
var req = client.putStream(res, elem._id, headers,function(err,s3res){
    if(err) console.log(err);
    console.log(s3res);
}).end();
```

This was  the last comment. Worked for the guy who posted the solution.

**Comment by JamesTheHacker** [comment]
The following solved it for me:

```
var http = require('http')
http.globalAgent.maxSockets = 2048
```

Some suggest `1024`, but I was still getting some errors. I upped to `2048` and works fine.

**Comment by droppedoncaprica** [comment]
I know this isn't StackOverflow, but for anyone coming into this issue in the future, make sure you call `.end()` on the `knoxClient.get()` call.

IE this will return a socket hangup...

```
client.get('s3-key')
.on('response', handleResponse)
.on('error', handleError);
```

and this will not

```
client.get('s3-key')
.on('response', checkHeadersAndStreamFile)
.on('error', handleError)
.end();
```

A pretty obvious coding error, but one that I usually end up running into when I add Knox to a new project.  :laughing:

**Comment by DaGaMs** [comment]
FWIW, I've had this problem when I was passing the request object into a callback function in Loopback. Long story short, the only thing that "fixed" the problem was to do `getFile(url, (err, res) => {callback(null, res)})` - in that way the data is streamed correctly.
