### ISSUE TITLE
CERT_UNTRUSTED on node v0.10.34

### ISSUE THREAD

**Issue by jonathanong** [Automattic/knox#264]
upgraded node and now i'm getting this error. can anyone verify? i don't have dots in my bucket. i'm wondering if this is a knox issue, a node issue, or my issue...

**Comment by juliangruber** [comment]
or upgrade to 0.10.35 http://blog.nodejs.org/2014/12/23/node-v0-10-35-stable/

**Comment by alireza-saberi** [comment]
@jurgelenas @juliangruber : Do you guys have  a direct command for it on terminal?

**Comment by juliangruber** [comment]
@alireza-saberi you can use a node version manager like nvm
