### ISSUE TITLE
mocking

### ISSUE THREAD

**Issue by timoxley** [Automattic/knox#45]
I'm having difficulties incorporating this library into my app as it's a bit tricky to set up a mocked version. Any tips?

**Comment by dylanjha** [comment]
For anyone else finding this thread (5+ years later!) I'm able to successfully use nock [nock](https://github.com/node-nock/nock) to mock knox http requests.

example:

```javascript
nock(`https://${bucketName}.s3.amazonaws.com`)
  .delete(`/${userId}/${file}`)
  .reply(200, { message: 'mocked' })

const knoxClient = knox({ key, secret, bucket })
// this request will be mocked with nock
knoxClient.deleteFile(`${this.userId}/${file}`)
```
